
image: macos-catalina


configuration: Release

platform: x64

before_build:
  - cmd: gitversion /l console /output buildserver

init:
  - echo This is the macos build script
  # - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-vnc.sh' | bash -e -
      
build_script:
  - sh: >-
      echo building on Mac
      gcc main.cpp -o app

after_build:
      echo After build
 
on_finish:
 - sh: export APPVEYOR_VNC_BLOCK=true
 - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-vnc.sh' | bash -e -
