environment:
  matrix:

  - job_name: Windows build
    appveyor_build_worker_image: Visual Studio 2017

  - job_name: Linux build
    appveyor_build_worker_image: Ubuntu1804

configuration: Release

platform: x64

before_build:
  - cmd: gitversion /l console /output buildserver
  
  - ps: |
        echo "BUILD_VERSION=`"$env:APPVEYOR_BUILD_VERSION`\n"  | Out-File -Encoding ascii version.txt
        type version.txt

artifacts:
  - path: 'app*'
    name: application

skip_commits:
  files:
    - docs/*
    - readme.txt
    
for:
  -
    matrix:
      only:
        - job_name: Linux build
    init:
      - echo Ubuntu build script
      - sh: >-
          sudo apt-get install -y libgl1-mesa-dev libxrandr-dev libxinerama-dev
          
    build_script:
      - sh: >-
          gcc main.cpp -o app
      
      - ps: |
          pwd
          type kalle.txt                 
          
    artifacts:
      - path: app
        name: test_app_release_ubuntu
  
  -
    matrix:
      only:
        - job_name: Windows build
        
    build_script:
      - echo Visual Studio 2017 x64 build script
      - cmd:
          call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
          
          cl main.cpp "/Fe:" app.exe



deploy:
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: test_appveyor $(GitVersion_MajorMinorPatch) (build $(APPVEYOR_BUILD_NUMBER))
    description: 'Automated release\nBinaries8'
    auth_token:
      secure: wKTE14vggGofMa87GvA3pLpShpKrkoFwaf50nFJsBu9JfTWsfqOE20skdO6Eg74u
    on:
       APPVEYOR_REPO_TAG: true       # deploy on tag push only
