
image:
- Visual Studio 2017


configuration: Release

platform: x64

before_build:
  - cmd: gitversion /l console /output buildserver  

build_script:
  - echo Visual Studio 2017 x64 build script

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))