
image:
- macos
- Visual Studio 2017
- Ubuntu1804


configuration: Release

platform: x64

before_build:
  - cmd: gitversion /l console /output buildserver

skip_commits:
  message: /#skip_build/

max_jobs: 2


artifacts:
  - path: dummy.txt
    name: MyArtifact

on_success:
  - ps: |
      echo "hello global"
      if ($Env:APPVEYOR_REPO_TAG -eq $true)
      {
          echo "Deploy"
      }

for:
  -
    matrix:
      only:
        - image: Ubuntu1804
    init:
      - echo Ubuntu build script
      # - sh: >-
      #     sudo apt-get install -y libgl1-mesa-dev libxrandr-dev libxinerama-dev
          
    build_script:
      - sh: >-
          echo "First line"
      
          gcc main.cpp -o app
      
          echo "Third line"
    
    after_build:
      - sh: >-
          if [[ $APPVEYOR_REPO_COMMIT_MESSAGE = *#store_bins* ]] || [ "$APPVEYOR_REPO_TAG" == "true" ]; 
          then 
            echo "Store binary artifacts";
            echo "dummy content" > dummy.txt;
          else
            echo "Do not store binary artifacts";
          fi
          
    test_script:
      - echo This is my custom test script
      - ps: |
          python3 return_arg.py 0
          $r0 = $LASTEXITCODE

          python3 return_arg.py 0
          $r1 = $LASTEXITCODE
          
          python3 return_arg.py 0
          $r2 = $LASTEXITCODE

          exit !(($r0 -eq 0) -and ($r1 -eq 0) -and ($r2 -eq 0))
          
    on_finish:
      - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))          
      
  -
    matrix:
      only:
        - image: Visual Studio 2017
        
    init:
      - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  
    build_script:
      - echo Visual Studio 2017 x64 build script
      - cmd:
          call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
          
          cl main.cpp "/Fe:" app.exe

    after_build:
      - ps: |
          if ($Env:APPVEYOR_REPO_COMMIT_MESSAGE -match '#store_bins' -Or $Env:APPVEYOR_REPO_TAG -eq $true)
          {
            echo "Store binary artifacts"
            echo "dummy content"  | Out-File -Encoding ascii dummy.txt            
          }
          else
          {
            echo "Do not store binary artifacts"
          }

    test_script:
      - echo This is my custom test script
      - ps: |
          C:/Python38/python return_arg.py 0
          $r0 = $LASTEXITCODE

          C:/Python38/python return_arg.py 0
          $r1 = $LASTEXITCODE
          
          C:/Python38/python return_arg.py 0
          $r2 = $LASTEXITCODE

          exit !(($r0 -eq 0) -and ($r1 -eq 0) -and ($r2 -eq 0))

  -
    matrix:
      only:
        - image: macos

    init:
      - echo This is the macos build script
      # - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-vnc.sh' | bash -e -
          
    build_script:
      - sh: >-
          echo building on Mac
          gcc main.cpp -o app

    after_build:
          if [[ $APPVEYOR_REPO_COMMIT_MESSAGE = *#store_bins* ]] || [ "$APPVEYOR_REPO_TAG" == "true" ]; 
          then 
            echo "Store binary artifacts";
            echo "dummy content" > dummy.txt;
          else
            echo "Do not store binary artifacts";
          fi

    test_script:
      - echo This is my custom test script
      - ps: |
          python3 return_arg.py 0
          $r0 = $LASTEXITCODE

          python3 return_arg.py 0
          $r1 = $LASTEXITCODE
          
          python3 return_arg.py 0
          $r2 = $LASTEXITCODE

          exit !(($r0 -eq 0) -and ($r1 -eq 0) -and ($r2 -eq 0))
          
    on_finish:
#      - sh: export APPVEYOR_VNC_BLOCK=true
#      - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-vnc.sh' | bash -e -

#deploy:
  # - provider: GitHub
  #   tag: $(APPVEYOR_REPO_TAG_NAME)
  #   release: test_appveyor $(GitVersion_MajorMinorPatch) (build $(APPVEYOR_BUILD_NUMBER))
  #   description: 'Demo and binaries. For information about changes and new features see [release notes](https://github.com/esmini/esmini/blob/master/release_notes.md).'
  #   auth_token:
  #     secure: wKTE14vggGofMa87GvA3pLpShpKrkoFwaf50nFJsBu9JfTWsfqOE20skdO6Eg74u
  #   on:
  #      APPVEYOR_REPO_TAG: true       # deploy on tag push only

