
image:
# - Visual Studio 2017
- Ubuntu1804

configuration: Release

platform: x64

before_build:
  - cmd: gitversion /l console /output buildserver  

build_script:
  - sh: >-

      echo Linux build script
      
      if [ 1 == 1 ];
      then
        echo first line

        echo second line

        ls -al

        echo third line
      fi
      
on_finish:
  - sh: export APPVEYOR_SSH_BLOCK=true
  - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -      

  # - echo Visual Studio 2017 x64 build script
  # - cmd:
  
      # set PATH="c:/Program Files/Git/bin";%PATH%
      
      # git clone https://github.com/esmini/esmini
      
      # cd esmini
      
      # git checkout update_hello_world
      
      # mkdir build
      
      # cd build
      
      # cmake -G "Visual Studio 15 Win64" ..
      
      # cmake --build . --config Release --target install
      
      # cd ..

      # set PATH="c:/Program Files/Git/bin";%PATH%

      # bash .\scripts\generate_binary_dist.sh
      
      # dir esmini-demo


# on_finish:
  # - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))