
image: macos-catalina


configuration: Release

platform: x64

before_build:
  - cmd: gitversion /l console /output buildserver

init:
  - echo This is the macos build script
  # - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-vnc.sh' | bash -e -
      
build_script:
  - sh: >-
      # chmod +x scripts/*

      # mkdir osg

      # cd osg

      # ../scripts/generate_osg_libs.sh

      # cd ..

on_finish:
  - sh: export APPVEYOR_VNC_BLOCK=true
  - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-vnc.sh' | bash -e -
  
artifacts:
    # - path: osg/osg_mac.7z
    #   name: osg_lib
