image:
- Visual Studio 2017
- Ubuntu1804

configuration: Release

platform: x64

before_build:
  - cmd: gitversion /l console /output buildserver
  
  - ps: |
        echo "BUILD_VERSION=`"$env:APPVEYOR_BUILD_VERSION`\n"  | Out-File -Encoding ascii version.txt
        type version.txt

artifacts:
  - path: /app.*/

skip_commits:
  message: /#dont-build/
  files:
    - docs/*
    - readme.txt

max_jobs: 2

for:
  -
    branches:
      only: 
      - master
    
    artifacts:
      path: version.txt

deploy:
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: test_appveyor $(GitVersion_MajorMinorPatch) (build $(APPVEYOR_BUILD_NUMBER))
    description: 'Automated release\nBinaries8'
    auth_token:
      secure: wKTE14vggGofMa87GvA3pLpShpKrkoFwaf50nFJsBu9JfTWsfqOE20skdO6Eg74u
    on:
       APPVEYOR_REPO_TAG: true       # deploy on tag push only
