image:
- Visual Studio 2017
- Ubuntu1804

configuration: Release

platform:
- x64

before_build:
  - cmd: gitversion /l console /output buildserver

for:
  -
    matrix:
      only:
        - image: Ubuntu1804
    init:
      - echo Ubuntu build script
      - sh: >-
          sudo apt-get install -y libgl1-mesa-dev libxrandr-dev libxinerama-dev
          
    build_script:
      - sh: >-
          gcc main.cpp -o app

    artifacts:
      - path: app
        name: test_app_release_ubuntu
  
  -
    matrix:
      only:
        - image: Visual Studio 2017
          platform: x64
    build_script:
      - echo Visual Studio 2017 x64 build script
      - cmd:
          call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
          
          cl main.cpp "/Fe:" app.exe

    artifacts:
      - path: app.exe
        name: test_app_release_win

deploy:
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: test_appveyor $(GitVersion_MajorMinorPatch) (build $(APPVEYOR_BUILD_NUMBER))
    description: 'Automated release\nBinaries2'  
    auth_token:
      secure: wKTE14vggGofMa87GvA3pLpShpKrkoFwaf50nFJsBu9JfTWsfqOE20skdO6Eg74u
    on:
       APPVEYOR_REPO_TAG: true       # deploy on tag push only
